services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend.dockerfile
      target: frontend
    image: ssumaiyaahmed/quirknotes_frontend:latest
    ports:
      - "3000:80"
    environment:
      - ENV=Docker
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend.dockerfile
      target: backend
    image: ssumaiyaahmed/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"